---
apiVersion: v2
name: app
version: 0.6.1
appVersion: 0.6.1
description: A Helm chart which provides a DRY application deployment mechanism
icon: "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
keywords:
  - application
  - template
  - DRY
  - generic
source:
  - https://github.com/aahemm/helm-microservice
maintainers:
  - name: aliakbar-hemmati
