name: microservice
version: 0.1.0
appVersion: 0.1.0
description: A Helm chart which provide a DRY microservice deployment mechanism
keywords:
  - microservice
  - template
source:
  - https://github.com/cetic/helm-microservice
maintainers:
  - name: terence-bigtt
  - name: alexnuttinck
