#Hub
enabled: true
# imagePullSecrets: []

imageCredentials:
  registry: https://index.docker.io/v1/
  username: tsorage
  password: "c427dde2-32b1-457e-9b5b-6b647aecd8f8"
  email: tsorage@cetic.be

createServiceAccount: false
rbac: false

image:
  repository: "tsorage/tsorage-hub"
  tag: 1.1.8
  pullPolicy: IfNotPresent

replicaCount: 1

services:
  - name: web
    type: ClusterIP
    annotations: {}
    specs:
    - port: 8081
      targetPort: 8081
      name: http

volumes:
  enabled: true
 # configFileCommonHeader:
  configMaps:
    - name: hub-conf
      mountPath: /var/config/hub
      data:
        licence: |
          end: 2022-01-01
          BV4n9g+9+wW+AQcyRplKhQGyhx5XASvMntrl7JrzCTZuFJ+rTZQ3JbKN0fjWzFwkTBuA21F5RCF4X/QtsZ0OgxvGlTlB1fSZ954wCeMmVu+i4HYQ1w1bjCfECMGazcPIBJ+/5yXXxuQUSyvWJuih+pUh34STxpjiP1FUv25aHVItoST+B1nEuFoNkUcUFwELz7s8JC+2Du5jx1FmxYNo2oEPijbNHSZc5aY9plaGemlgkUaS75R/yLqtV0Ujb0f5OxMnZ1VkYbBOryzxBnAf7PwtWLLslalc+ee4T6tUffOZJJKo3vpM63msw8//z8yJtfija3hmIAVefsTv6MoCdQ==
        public.key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjOVR4yN1H75BsnJOR85SJ4KdwcN+GmnOEH7J2PpPTI1l0hBllMTueWC7512HDs0zdLJl4MP6CSW2TZyHCavIMJ/EzAvIOXJ90L1BPHTuI66ea446mWlqZDcVF2FFapO+AGMWYfeYwbH+QS3q4dHX5jQkL7WcRVj82ms87VFmaXbqcMAiXHG7cl3BiCKgiCKrzp8CDfgvqJmjexAK1PYTmS5DJm5rhmDuBfhhAiE08RItNO7HmTs88sRhq2/7Bpe9amX/jaEY/18twZ0t9nXjf8KJUlr0PZFMNfwa8VxQxQhQCF7qy7SWVfz6z70lrHfprjjrfMG/B7ux9qerPFNJfQIDAQAB
        hub.conf: |
          license {
            license = "/var/config/hub/license"
            public_key = "/var/config/hub/public.key"
          }

          host = 0.0.0.0
          port = 8081
              backend {
                name = "mockup"
              }

              sharder = "month"

              cassandra {
                  nodes = [
                      {
                          host = tsorage-cassandra.{{.Release.Namespace}}.svc.cluster.local
                          port = 9042
                      }
                  ]

                  security = {
                    type = "password"
                    login = "tsorage"
                    password = "tsorage"
                  }

                  keyspaces {
                      raw = "tsorage_ts"
                      other = "tsorage"
                  }

                  writeConsistencyLevel = "LOCAL_ONE"
                  readConsistencyLevel = "LOCAL_ONE"
              }

              promql {
                history_window = 5 minutes
                sparse_limit = 1 hour
              }

              api {
                prefix = "/api/v1"
                version = "v1"
              }

              anomaly_monitoring {
                  active_revision_table = "active_anomaly_monitor_revision"
                  anomaly_monitor_table = "anomaly_monitor_revision"

                  kafka = {
                      topic = "anomaly_monitoring",
                      type = "flow/kafka/json"
                      nodes = [
                          {
                              host = tsorage-kafka.{{.Release.Namespace}}.svc.cluster.local
                              port = 9092
                          }
                      ],
                      security = {
                          type = "anonymous"
                      }
                  }
              }