global:
  replicaCount: 1

image:
  repository: "nginx"
  tag: "1.24.0"
  pullPolicy: Always

services:
- name: web
  type: NodePort
  annotations: {}
  specs:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: web

volumes:
  enabled: true
  pvc:
    enabled: false
  configMaps: 
  - name: nginx-config
    mountPath: /etc/nginx/conf.d/
    data:
      default.conf: |
        server {
          listen 80;
          listen [::]:80;

          server_name www.example.com;
              
          location / {
              proxy_pass http://localhost:8000;
              proxy_set_header Host $http_host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
        }
          
resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi
