global:
  replicaCount: 1

image:
  repository: "aahemm/podinfo"
  tag: "v0.12.0"
  pullPolicy: IfNotPresent

volumes:
  enabled: true
  pvc:
    enabled: false
  secrets:
  - name: test-secret
    mountPath: /test-secret
  - name: test-secret-2
    mountPath: /etc/myfile.conf
    subPath: myfile.conf
  configMaps: []
